datasource:
  url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=true
  username: root
  password:
  driver-class-name: com.mysql.jdbc.Driver
  testOnBorrow: true
  validationQuery: SELECT 1
system:
  cron: "0/10 * * * * ?"
server:
  port: 8000